### PR TITLE
Tag line book modal

### PR DESCRIPTION
**Pull request by btsolmonkhuu**
image

### CODE REVIEW

**Review by jakeaturner — CHANGES_REQUESTED** [review]
@btsolmonkhuu  can you do the CSS changes with [tailwinds classes](https://tailwindcss.com/docs/installation)? We're trying to utilize this more to try and get rid of one-off CSS files. For example this one would be 'text-center font-bold'.

**Review by jakeaturner — APPROVED** [review]
JT 3/14/24

**Comment by btsolmonkhuu** [comment]
@jakeaturner just made the change! This is my first time using tailwind css so please let me know if there is any issue! Out of curiosity, what's the benefit of using tailwind vs inline or having a styles sheet?

**Comment by jakeaturner** [comment]
@btsolmonkhuu thanks! At the end of the day, they all accomplish the same thing, but tailwinds is nice because its essentially just a huge collection of 'utility' classes that we can throw in to elements really quick. For example, if all we need is a paragraph element with bold, red font and a little bit of margin on the top we can just do:
`className='text-red-500 font-bold mt-1`

vs. `.myParagraph {
color: #redhexcode;
font-weight: italic;
margin;-top: 5px;
}`
 and then we don't have to worry about bloating the repo with a bunch of small css files or making things hard to read with inline styles. Though, having defining explicit classes is still totally justifiable in some cases, like when you need to really customize the heck out of an element.

**Pull request merged**
